create schema db_account;
create schema db_authenticate;
create schema db_bankaccount;
create schema db_catalog;
create schema db_creditcard;
create schema db_inventory;
create schema db_order;
create schema db_payment;
create schema db_shipping;