apiVersion: v1
kind: ConfigMap
metadata:
  name: account-service
  namespace: default
data:
  MYSQL_PASSWORD: password
  SERVICE_API_KEY: vanapikey
  AUTHENTICATE_SERVICE: authentication-service.default.svc.cluster.local:8888
