apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service
  namespace: default
data:
  MYSQL_PASSWORD: password
  SERVICE_API_KEY: vanapikey
  AUTHENTICATE_SERVICE: authentication-service
  PAYMENT_SERVICE: payment-service
  SHIPPING_SERVICE: shipping-service
  CATALOG_SERVICE: catalogue-service