apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service
  namespace: default
data:
  MYSQL_PASSWORD: password
  SERVICE_API_KEY: vanapikey
  bankaccountsvc: bankpayment-service.default.svc.cluster.local:8001
  creditcardsvc: creditcardpayment-service.default.svc.cluster.local:8002
  paypalsvc: paypalpayment-service.default.svc.cluster.local:8003