apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
  labels:
    app: account-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
        - name: account-service
          image: islamahmad/ea02account:1.0.2
          env:
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PORT
              value: "3306"
            - name: SERVICE_API_KEY
              valueFrom:
                configMapKeyRef:
                  name: account-service
                  key: SERVICE_API_KEY
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: account-service
                  key: MYSQL_PASSWORD
            - name: AUTHENTICATE_SERVICE
              valueFrom:
                configMapKeyRef:
                 name: account-service
                 key: AUTHENTICATE_SERVICE