apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-service
  labels:
    environment: dev
    app: authentication-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication-service
  template:
    metadata:
      labels:
        app: authentication-service
    spec:
      containers:
        - name: authentication-service
          image: islamahmad/ea02authentication:1.0.0
            ports:
                - containerPort: 8888