apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankpayment-service
  labels:
    environment: dev
    app: bankpayment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bankpayment-service
  template:
    metadata:
      labels:
        app: bankpayment-service
    spec:
      containers:
        - name: bankpayment-service
          image: islamahmad/ea02bankpayment:1.0.0
            ports:
                - containerPort: 8001
