apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankpayment-service
  labels:
    app: bankpayment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bankpayment-service
  template:
    metadata:
      labels:
        app: bankpayment-service
    spec:
      containers:
        - name: bankpayment-service
          image: islamahmad/ea02bankpayment:1.0.0
          env:
              - name: MYSQL_HOST
                value: mysql
              - name: MYSQL_USER
                value: root
              - name: MYSQL_PORT
                value: "3306"
              - name: SERVICE_API_KEY
                valueFrom:
                  configMapKeyRef:
                    name: bankpayment-service
                    key: SERVICE_API_KEY
              - name: MYSQL_PASSWORD
                valueFrom:
                  configMapKeyRef:
                    name: bankpayment-service
                    key: MYSQL_PASSWORD
