apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue-service
  labels:
    app: catalogue-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogue-service
  template:
    metadata:
      labels:
        app: catalogue-service
    spec:
      containers:
        - name: catalogue-service
          image: islamahmad/ea02catalogue:1.0.1
          env:
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PORT
              value: "3306"
            - name: SERVICE_API_KEY
              valueFrom:
                configMapKeyRef:
                  name: catalogue-service
                  key: SERVICE_API_KEY
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: catalogue-service
                  key: MYSQL_PASSWORD