apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue-service
  labels:
    environment: dev
    app: catalogue-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogue-service
  template:
    metadata:
      labels:
        app: catalogue-service
    spec:
      containers:
        - name: catalogue-service
          image: islamahmad/ea02catalogue:1.0.0
            ports:
                - containerPort: 8002