apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  labels:
    environment: dev
    app: inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service