apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    environment: dev
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: islamahmad/ea02order:1.0.0
          env:
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PORT
              value: "3306"
            - name: SERVICE_API_KEY
              valueFrom:
                configMapKeyRef:
                  name: order-service
                  key: SERVICE_API_KEY
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: order-service
                  key: MYSQL_PASSWORD
            - name: AUTHENTICATE_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: order-service
                  key: AUTHENTICATE_SERVICE
            - name: PAYMENT_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: order-service
                  key: PAYMENT_SERVICE
            - name: SHIPPING_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: order-service
                  key: SHIPPING_SERVICE