apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    environment: dev
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service