apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  labels:
    environment: dev
    app: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: islamahmad/ea02payment:1.0.0
            ports:
                - containerPort: 8006