apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-service
  labels:
    environment: dev
    app: shipping-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping-service
  template:
    metadata:
      labels:
        app: shipping-service
    spec:
      containers:
        - name: shipping-service
          image: islamahmad/ea02shipping:1.0.0
            ports:
                - containerPort: 8008